"""ATT&CK Navigator layer generator.

Produces a JSON file compatible with the MITRE ATT&CK Navigator web tool
(https://mitre-attack.github.io/attack-navigator/). Judges can load it
and instantly see technique coverage — color-coded by confidence level.

Layers are built from:
1. Hunt pattern findings (find_evil results with technique IDs)
2. Verification results (confidence levels per technique)
3. Correction data (techniques that were flagged as FP/unsupported)

Color scheme:
  CONFIRMED → red (definitive evidence of technique)
  PARTIAL   → orange (some evidence, some unverified)
  INFERENCE → yellow (plausible but structurally unverified)
  INSUFFICIENT_EVIDENCE → not colored (excluded from layer)
  CORRECTED/FP → grey with strikethrough comment
"""

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


# ATT&CK Navigator layer schema version
NAVIGATOR_VERSION = "4.5"
ATTACK_VERSION = "15"  # ATT&CK v15 (2024)

# Color mapping for confidence levels
CONFIDENCE_COLORS = {
    "CONFIRMED": "#ff0000",      # Red — definitive evidence
    "PARTIAL": "#ff6600",        # Orange — partial evidence
    "INFERENCE": "#ffcc00",      # Yellow — plausible but unverified
    "CORRECTED": "#999999",      # Grey — flagged as FP/unsupported
}

# Score mapping (Navigator uses 0-100 numeric scores)
CONFIDENCE_SCORES = {
    "CONFIRMED": 100,
    "PARTIAL": 75,
    "INFERENCE": 50,
    "CORRECTED": 10,
}


def generate_navigator_layer(
    techniques: list[dict],
    name: str = "graphir Investigation",
    description: str = "",
) -> dict:
    """Generate an ATT&CK Navigator layer from technique observations.

    Args:
        techniques: List of dicts, each with:
            - technique_id: ATT&CK technique ID (e.g., 'T1059', 'T1059.001')
            - tactic: ATT&CK tactic name
            - confidence: CONFIRMED/PARTIAL/INFERENCE/CORRECTED
            - description: What was found
            - hit_count: Number of findings (optional)
        name: Layer name
        description: Layer description

    Returns:
        Navigator layer as dict (JSON-serializable)
    """
    # Deduplicate and keep highest confidence per technique
    technique_map: dict[str, dict] = {}
    for t in techniques:
        tid = t.get("technique_id", "")
        if not tid:
            continue

        confidence = t.get("confidence", "INFERENCE")
        existing = technique_map.get(tid)

        # Keep the highest confidence level for each technique
        if not existing or _confidence_rank(confidence) > _confidence_rank(existing["confidence"]):
            technique_map[tid] = t

    # Build technique entries
    layer_techniques = []
    for tid, t in technique_map.items():
        confidence = t.get("confidence", "INFERENCE")
        color = CONFIDENCE_COLORS.get(confidence, "#ffffff")
        score = CONFIDENCE_SCORES.get(confidence, 0)

        entry = {
            "techniqueID": tid,
            "color": color,
            "score": score,
            "comment": _build_comment(t),
            "enabled": True,
            "showSubtechniques": True,
        }

        # Add tactic if specified (for positioning in the matrix)
        tactic = t.get("tactic", "")
        if tactic:
            entry["tactic"] = _normalize_tactic(tactic)

        layer_techniques.append(entry)

    # Build the layer
    layer = {
        "name": name,
        "versions": {
            "attack": ATTACK_VERSION,
            "navigator": NAVIGATOR_VERSION,
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": description or f"Generated by graphir on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "filters": {
            "platforms": ["Windows"],
        },
        "sorting": 3,  # Sort by score descending
        "layout": {
            "layout": "side",
            "aggregateFunction": "max",
            "showID": True,
            "showName": True,
            "showAggregateScores": True,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": layer_techniques,
        "gradient": {
            "colors": ["#ffffff", "#ffcc00", "#ff6600", "#ff0000"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "CONFIRMED (structural evidence)", "color": CONFIDENCE_COLORS["CONFIRMED"]},
            {"label": "PARTIAL (some evidence)", "color": CONFIDENCE_COLORS["PARTIAL"]},
            {"label": "INFERENCE (plausible, unverified)", "color": CONFIDENCE_COLORS["INFERENCE"]},
            {"label": "CORRECTED (flagged as FP)", "color": CONFIDENCE_COLORS["CORRECTED"]},
        ],
        "metadata": [
            {"name": "tool", "value": "graphir"},
            {"name": "generated", "value": datetime.now(timezone.utc).isoformat()},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
    }

    return layer


def generate_layer_from_findings(run_cypher, findings: list[dict]) -> dict:
    """Generate Navigator layer from find_evil results + graph corrections.

    Pulls technique IDs from hunt findings and checks for existing
    corrections to mark techniques as CORRECTED.
    """
    techniques = []

    # Extract techniques from findings
    for finding in findings:
        technique = finding.get("technique", "")
        tactic = finding.get("tactic", "")
        hit_count = finding.get("hit_count", 0)
        hunt = finding.get("hunt", "")

        if not technique:
            continue

        techniques.append({
            "technique_id": technique,
            "tactic": tactic,
            "confidence": "INFERENCE",  # Default — findings haven't been verified yet
            "description": finding.get("description", ""),
            "hit_count": hit_count,
            "source": f"hunt:{hunt}",
        })

    # Check for corrections that should downgrade techniques
    try:
        corrections = run_cypher("""
            MATCH (c:Correction)
            WHERE c.type IN ['false_positive', 'unsupported', 'hallucination']
            RETURN c.original_claim AS claim, c.type AS correction_type,
                   c.reason AS reason
        """)
        # Only downgrade if the technique is NOT already CONFIRMED.
        # A correction on one instance of a technique should not hide
        # a confirmed finding of the same technique elsewhere.
        for c in corrections:
            claim = (c.get("claim") or "").lower()
            finding_id = c.get("finding_id", "")
            for t in techniques:
                if t["technique_id"].lower() in claim and t.get("confidence") != "CONFIRMED":
                    t["confidence"] = "CORRECTED"
                    t["description"] += f" [CORRECTED: {c.get('reason', '')}]"
    except Exception:
        pass  # Corrections are optional enhancement

    return generate_navigator_layer(
        techniques,
        name="graphir Investigation",
        description="Auto-generated from autonomous IR investigation findings",
    )


def write_navigator_layer(layer: dict,
                          output_path: str = "investigation-output/navigator-layer.json") -> dict:
    """Write Navigator layer to JSON file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w") as f:
        json.dump(layer, f, indent=2)

    technique_count = len(layer.get("techniques", []))
    return {
        "status": "ok",
        "path": str(path),
        "techniques_mapped": technique_count,
    }


# --- Helpers ---

def _confidence_rank(confidence: str) -> int:
    """Rank confidences for dedup (higher = keep)."""
    ranks = {"CONFIRMED": 4, "PARTIAL": 3, "INFERENCE": 2, "CORRECTED": 1}
    return ranks.get(confidence, 0)


def _normalize_tactic(tactic: str) -> str:
    """Normalize tactic name to ATT&CK Navigator format."""
    tactic_map = {
        "execution": "execution",
        "lateral movement": "lateral-movement",
        "lateral_movement": "lateral-movement",
        "credential access": "credential-access",
        "credential_access": "credential-access",
        "persistence": "persistence",
        "defense evasion": "defense-evasion",
        "defense_evasion": "defense-evasion",
        "discovery": "discovery",
        "collection": "collection",
        "exfiltration": "exfiltration",
        "command and control": "command-and-control",
        "initial access": "initial-access",
        "privilege escalation": "privilege-escalation",
        "impact": "impact",
    }
    return tactic_map.get(tactic.lower(), tactic.lower().replace(" ", "-"))


def _build_comment(technique: dict) -> str:
    """Build a Navigator comment from technique data."""
    parts = []
    confidence = technique.get("confidence", "")
    if confidence:
        parts.append(f"Confidence: {confidence}")
    desc = technique.get("description", "")
    if desc:
        parts.append(desc)
    hits = technique.get("hit_count", 0)
    if hits:
        parts.append(f"Hits: {hits}")
    source = technique.get("source", "")
    if source:
        parts.append(f"Source: {source}")
    return " | ".join(parts)
