"""Report renderer — markdown → PDF / DOCX / markdown.

Takes the audit report markdown (already generated by audit_report.py) and
renders it to multiple output formats. Markdown is the source of truth;
PDF and DOCX are render targets for different audiences.

Rendering chain:
  audit_report.py → audit-report.md (source)
    → pandoc → audit-report.pdf  (board/legal)
    → pandoc → audit-report.docx (analyst copy-paste)
    → copy   → audit-report.md   (IR team, version control)

Requires pandoc installed (available on SIFT Workstation).
PDF rendering requires a LaTeX engine (pdflatex/xelatex) or uses HTML fallback.
"""

import json
import shutil
import subprocess
from pathlib import Path


def render_report(markdown_path: str,
                  output_dir: str = "investigation-output",
                  formats: list[str] | None = None) -> dict:
    """Render a markdown report to multiple formats.

    Args:
        markdown_path: Path to the source markdown file.
        output_dir: Directory for output files.
        formats: List of formats to render. Default: ["md", "pdf", "docx"].
                 Supported: "md", "pdf", "docx", "html".

    Returns:
        Dict with paths to rendered files and any errors.
    """
    if formats is None:
        formats = ["md", "pdf", "docx"]

    md_path = Path(markdown_path)
    if not md_path.exists():
        return {"error": f"Markdown file not found: {markdown_path}"}

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    stem = md_path.stem
    results = {"source": str(md_path), "rendered": {}, "errors": []}

    # Check pandoc
    pandoc = shutil.which("pandoc")
    if not pandoc and any(f in formats for f in ["pdf", "docx", "html"]):
        results["errors"].append(
            "pandoc not found. Install pandoc for PDF/DOCX/HTML rendering. "
            "On SIFT: sudo apt install pandoc"
        )

    for fmt in formats:
        try:
            if fmt == "md":
                # Just copy the markdown
                dest = out_dir / f"{stem}.md"
                if md_path != dest:
                    shutil.copy2(md_path, dest)
                results["rendered"]["md"] = str(dest)

            elif fmt == "pdf" and pandoc:
                dest = out_dir / f"{stem}.pdf"
                success = _render_pdf(pandoc, md_path, dest)
                if success:
                    results["rendered"]["pdf"] = str(dest)
                else:
                    results["errors"].append("PDF rendering failed — see details")

            elif fmt == "docx" and pandoc:
                dest = out_dir / f"{stem}.docx"
                _render_docx(pandoc, md_path, dest)
                results["rendered"]["docx"] = str(dest)

            elif fmt == "html" and pandoc:
                dest = out_dir / f"{stem}.html"
                _render_html(pandoc, md_path, dest)
                results["rendered"]["html"] = str(dest)

        except Exception as e:
            results["errors"].append(f"{fmt}: {str(e)}")

    return results


def _render_pdf(pandoc: str, md_path: Path, dest: Path) -> bool:
    """Render markdown to PDF via pandoc.

    Tries pdflatex first, falls back to HTML→wkhtmltopdf,
    then falls back to HTML output with a note.
    """
    # Try pdflatex engine first
    result = subprocess.run(
        [pandoc, str(md_path), "-o", str(dest),
         "--pdf-engine=pdflatex",
         "-V", "geometry:margin=2.5cm",
         "-V", "fontsize=11pt",
         "--highlight-style=tango",
         "-f", "markdown",
         "--metadata", "title=graphir Investigation Report"],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode == 0:
        return True

    # Try xelatex
    result = subprocess.run(
        [pandoc, str(md_path), "-o", str(dest),
         "--pdf-engine=xelatex",
         "-V", "geometry:margin=2.5cm",
         "-f", "markdown"],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode == 0:
        return True

    # Fallback: render as HTML (rename to .pdf.html)
    html_dest = dest.with_suffix(".pdf.html")
    _render_html(pandoc, md_path, html_dest)
    return False


def _render_docx(pandoc: str, md_path: Path, dest: Path):
    """Render markdown to DOCX via pandoc."""
    result = subprocess.run(
        [pandoc, str(md_path), "-o", str(dest),
         "-f", "markdown",
         "--metadata", "title=graphir Investigation Report"],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode != 0:
        raise RuntimeError(f"pandoc docx failed: {result.stderr[:300]}")


def _render_html(pandoc: str, md_path: Path, dest: Path):
    """Render markdown to standalone HTML via pandoc."""
    result = subprocess.run(
        [pandoc, str(md_path), "-o", str(dest),
         "-f", "markdown",
         "--standalone",
         "--metadata", "title=graphir Investigation Report",
         "--highlight-style=tango"],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode != 0:
        raise RuntimeError(f"pandoc html failed: {result.stderr[:300]}")
